version: "3"
services:
    main:
        container_name: main
        build:
            context: .
            dockerfile: ./Dockerfile
        # image: docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest
        # command: npm run start:dev

        # volumes:
        #     - ./src:/backend/src
        ports:
            - 3000:3000
        networks:
            - postgres
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./conf.d/:/etc/nginx/conf.d
        depends_on:
            - main
        networks:
            - postgres

networks:
    postgres:
        driver: bridge

# volumes:
#   demo:
